### ISSUE TITLE
[RNGlobalize] Error processing message welcome

### ISSUE THREAD

**Issue by JerryBels** [joshswan/react-native-globalize#63]
Hello guys,

1/ Trying to implement this solution, I simply integrated the basic code into my fairly new project. Simplifying my code : 

App.tsx: 

``` javascript
import React from 'react';
import { GlobalizeProvider, loadCldr } from 'react-native-globalize';
import fr from 'react-native-globalize/locale-data/fr';
import { NavigationContainer } from '@react-navigation/native';
import { MainRoutes, MainStack } from './src/routing/mainRoutes';
import AuthNavigator from './src/routing/AuthNavigation';

export default function App(): React.ReactElement {
  loadCldr(fr);

  return (
    <GlobalizeProvider locale="fr" currency="USD" defaultLocale="en">
      <NavigationContainer>
        <MainStack.Navigator headerMode="none">
          <MainStack.Screen name={MainRoutes.Auth} component={AuthNavigator} />
        </MainStack.Navigator>
      </NavigationContainer>
    </GlobalizeProvider>
  );
}
```

Navigation defaults to SignupScreen.tsx:

``` javascript
import React from 'react';
import { View, Text } from 'react-native';
import { loadMessages, useGlobalize } from 'react-native-globalize';

loadMessages({
  de: {
    welcome: 'Hallo, heute ist der {date}',
  },
  en: {
    welcome: 'Hello, today is {date}',
  },
  es: {
    welcome: 'Hola, hoy es {date}',
  },
});

const SignupScreen = (): React.ReactElement => {
  const { formatDate, formatMessage } = useGlobalize();

  return (
    <View>
      <Text>
        {formatMessage('welcome', {
          date: formatDate(new Date(), { date: 'long' }),
        })}
        {formatDate(new Date(2020, 0, 1))}
      </Text>
    </View>
  );
};

export default SignupScreen;
```

I'm getting an error : 

```
[RNGlobalize] Error processing message welcome.
createError@http://10.90.90.176:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:117713:24
validate@http://10.90.90.176:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:117810:26
validateMessageBundle@http://10.90.90.176:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:120871:15
messageFormatter@http://10.90.90.176:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:120975:28
[native code]
http://10.90.90.176:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:124914:40
http://10.90.90.176:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:117554:48
formatMessage@http://10.90.90.176:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:124976:33
formatMessage@[native code]
SignupScreen@http://10.90.90.176:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:151262:21
renderWithHooks@http://10.90.90.176:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:16187:33
mountIndeterminateComponent@http://10.90.90.176:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:18283:34
beginWork$1@http://10.90.90.176:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:22715:29
performUnitOfWork@http://10.90.90.176:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:21907:29
workLoopSync@http://10.90.90.176:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:21850:45
renderRootSync@http://10.90.90.176:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:21823:25
performSyncWorkOnRoot@http://10.90.90.176:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:21594:40
performSyncWorkOnRoot@[native code]
http://10.90.90.176:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:12883:38
unstable_runWithPriority@http://10.90.90.176:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:54012:30
flushSyncCallbackQueueImpl@http://10.90.90.176:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:12878:28
flushSyncCallbackQueue@http://10.90.90.176:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:12867:35
scheduleUpdateOnFiber@http://10.90.90.176:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:21220:37
updateContainer@http://10.90.90.176:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:23699:21
render@http://10.90.90.176:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:24133:24
renderApplication@http://10.90.90.176:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:81860:77
run@http://10.90.90.176:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:81430:28
runApplication@http://10.90.90.176:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:81487:28
__callFunction@http://10.90.90.176:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:3255:36
http://10.90.90.176:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:2987:31
__guard@http://10.90.90.176:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:3209:15
callFunctionReturnFlushedQueue@http://10.90.90.176:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:2986:21
callFunctionReturnFlushedQueue@[native code]
at node_modules/react-native-globalize/dist/globalize/utils.js:44:8 in logError
at node_modules/react-native-globalize/dist/globalize/formatters/message.js:24:12 in <anonymous>
at node_modules/react-native-globalize/dist/globalize/cache.js:33:25 in <anonymous>
at node_modules/react-native-globalize/dist/globalize/formatters/message.js:64:34 in formatMessage
at [native code]:null in formatMessage
at src/screens/auth/SignupScreen.tsx:23:22 in SignupScreen
at [native code]:null in performSyncWorkOnRoot
at node_modules/react-native/Libraries/ReactNative/renderApplication.js:54:4 in renderApplication
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:117:25 in runnables.appKey.run
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:213:4 in runApplication
at [native code]:null in callFunctionReturnFlushedQueue
```

2/ Also, side note, the line `import fr from 'react-native-globalize/locale-data/fr';` gives me this typescript warning:

```
TS7016: Could not find a declaration file for module 'react-native-globalize/locale-data/fr'. '/storage/buddzy/node_modules/react-native-globalize/locale-data/fr.js' implicitly has an 'any' type.   Try `npm install @types/react-native-globalize` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-globalize/locale-data/fr';`
```

I'm on the latest expo version, and using react-navigation.

**Comment by joshswan** [comment]
Hey @JerryBels, the error is due to the fact you're using `fr` for your locale but have no `fr` key in your messages.

As for the TS error, I'd recommend either ignoring it (generally or using comments) or using require for loading the locale data. Those files shouldn't be interacted with directly anyway so it seems a waste to ship empty declaration files for each one.
